general:
  save_path:  './example_output'
  model_path: 'runwayml/stable-diffusion-v1-5'
  unet_config: './conf/unet/config.json'
  real_image_editing: False
  controlnet_path: 'lllyasviel/sd-controlnet-depth'
  depth_estimator: 
    type: 'depth-estimation'
    path: 'Intel/dpt-large'
  openai_api_key: 'your_openai_api_key'

inference:
  loss_scale: 30
  batch_size: 1
  loss_threshold: 0.5
  max_iter: 10
  max_index_step: 10
  timesteps: 61
  classifier_free_guidance: 7.5
  rand_seed: 42

noise_schedule:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "scaled_linear"
  num_train_timesteps: 1000

real_image_editing:
  dreambooth_path: ''
  text_inversion_path: ''
  placeholder_token: '<sks>'